### ISSUE TITLE
Too many opened files.

### ISSUE THREAD

**Issue by w33ble** [wearefractal/lute#1]
I tried to use lute with some bower components and it keeps crashing with `Error: EMFILE: Too many opened files.`

It would be cool if lute would ignore `bower_components` by default, and even cooler if it would parse your `.bowerrc` and ignore the `directory` setting.

I'll probably work on a PR for this.

It's worth nothing that this seems to be a limitation of `gaze`.

**Comment by yocontra** [comment]
+1 this is a travesty - the author of this lib needs to fix this ASAP before they lose all credibility. Personally I am 100% fed up and I'm switching to bower for all future serving needs
