### ISSUE TITLE
How to disable LiveReload?

### ISSUE THREAD

**Issue by sole** [wearefractal/lute#13]
Hey, awesome little project, thanks! :-)

It's going to be great for most of what I do, but LiveReload is messing with my HTML imports:

![screenshot 2014-07-12 17 48 10](https://cloud.githubusercontent.com/assets/5609/3562190/588450a4-09e4-11e4-8cdb-80e85e5b6c7c.png)

A solution, other than telling LiveReload to ignore some paths, would be to entirely disable it when firing up the server.

It's not mentioned in the options in the README and the code doesn't seem to allow to _not_ LiveReload since [it all goes through the LiveReload object](https://github.com/wearefractal/lute/blob/ce68891b378986893fe15a74c8f8efdf1d7a4e57/lib/serve/index.js#L13-L17) but maybe I am not reading it right and this is in fact possible.

Help? :)

**Comment by funkytek** [comment]
hadn't tested with HTML imports, will look into this

**Comment by yocontra** [comment]
should be fixed with 0.0.3

There wasn't a lot of documentation here, but it seems like `window.self === window.top` should be false when in an iframe or an html import. I tested in chrome and that seemed to be the case. Let me know if it isn't in firefox.

**Comment by yocontra** [comment]
0.0.4 disabled injection in favor of using the extension
